### ISSUE TITLE
Has to have whitespace in order to start?

### ISSUE THREAD

**Issue by mitchweaver** [gyim/vim-boxdraw#13]
Sorry if this is a misunderstanding, but do you have whitespace dumped in a file in order to start drawing with boxdraw? If I go into visual mode, I can only "select" areas where there is text within the file.

Ideally I'd like to open a new, blank file and start drawing diagrams immediately.
Maybe a vim macro to help? dump say 20 lines of 72char columns of whitespace?

**Comment by gyim** [comment]
If you `set virtualedit+=all`, you only need a few blank lines. So I typically do `20o<Esc>` and `]ov` and I'm ready to start (the `]ov` mapping is provided by Tim Pope's [vim-unimpaired](https://github.com/tpope/vim-unimpaired) plugin).
